steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'us-west1-docker.pkg.dev/ardent-435422/ardent-webapp-repository/ardent-web-app', '.']
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'us-west1-docker.pkg.dev/ardent-435422/ardent-webapp-repository/ardent-web-app']
    - name: 'gcr.io/cloud-builders/gcloud'
      args: ['run', 'deploy', 'ardent-webapp', '--image', 'us-west1-docker.pkg.dev/ardent-435422/ardent-webapp-repository/ardent-web-app', '--platform=managed', '--region=us-west1', '--port=80', ]
logsBucket: 'ardent-435422_cloudbuild'
serviceAccount: 'projects/ardent-435422/serviceAccounts/ardent-service-account@ardent-435422.iam.gserviceaccount.com'
options:  
  logging: GCS_ONLY